# Generated by Django 5.0.6 on 2024-06-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonAppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('input_ds_schema', models.JSONField()),
                ('input_df_schema', models.JSONField(blank=True)),
                ('output_df_schema', models.JSONField(blank=True)),
                ('has_status', models.BooleanField()),
                ('has_current_state', models.BooleanField()),
            ],
            options={
                'db_table': 'monapptypes',
            },
        ),
        migrations.CreateModel(
            name='MonApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_state', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Stopped'), (2, 'Catching up'), (3, 'Running'), (4, 'Warning'), (5, 'Error')], default=1)),
                ('input_ds_schema', models.JSONField()),
                ('input_df_schema', models.JSONField(blank=True)),
                ('output_df_schema', models.JSONField(blank=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=0, null=True)),
                ('current_state', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=0, null=True)),
                ('prev_status', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=0, null=True)),
                ('prev_current_state', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=0, null=True)),
                ('status_use', models.IntegerField(choices=[(0, "Don't use at all"), (1, 'All as warning'), (2, 'As is')], default=2)),
                ('current_state_use', models.IntegerField(choices=[(0, "Don't use at all"), (1, 'All as warning'), (2, 'As is')], default=2)),
                ('retain', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monapplications.monapptype')),
            ],
            options={
                'db_table': 'monapplications',
            },
        ),
    ]
