# Generated by Django 5.0.6 on 2024-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monapplication',
            old_name='input_df_schema',
            new_name='input_datafeeds',
        ),
        migrations.RenameField(
            model_name='monapplication',
            old_name='output_df_schema',
            new_name='output_datafeeds',
        ),
        migrations.RemoveField(
            model_name='monapplication',
            name='input_ds_schema',
        ),
        migrations.RemoveField(
            model_name='monapplication',
            name='retain',
        ),
        migrations.AddField(
            model_name='monapplication',
            name='input_datastreams',
            field=models.JSONField(blank=True, default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monapplication',
            name='state',
            field=models.JSONField(blank=True, default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_ds_schema',
            field=models.JSONField(blank=True),
        ),
    ]
