# Generated by Django 5.0.6 on 2024-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0002_rename_input_df_schema_monapplication_input_datafeeds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monapplication',
            name='app_data',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monapptype',
            name='app_data_schema',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
