# Generated by Django 5.0.6 on 2024-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0003_monapplication_app_data_monapptype_app_data_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monapplication',
            name='app_data',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datafeeds',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datastreams',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='output_datafeeds',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='state',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='app_data_schema',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_df_schema',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_ds_schema',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='output_df_schema',
            field=models.JSONField(default='{}'),
        ),
    ]
