# Generated by Django 5.0.6 on 2024-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0004_alter_monapplication_app_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monapplication',
            name='state',
            field=models.JSONField(default=dict),
        ),
    ]
