# Generated by Django 5.0.6 on 2024-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0005_alter_monapplication_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monapplication',
            name='app_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datafeeds',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datastreams',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='output_datafeeds',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='app_data_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_df_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_ds_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='output_df_schema',
            field=models.JSONField(default=dict),
        ),
    ]
