# Generated by Django 5.0.6 on 2024-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapplications', '0006_alter_monapplication_app_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monapplication',
            name='app_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datafeeds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='input_datastreams',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='output_datafeeds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapplication',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='app_data_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_df_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='input_ds_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monapptype',
            name='output_df_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
