# Generated by Django 5.0.6 on 2024-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('current_state', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('prev_status', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('prev_current_state', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'OK'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('status_use', models.IntegerField(choices=[(0, "Don't use at all"), (1, 'All as warning'), (2, 'As is')], default=2)),
                ('current_state_use', models.IntegerField(choices=[(0, "Don't use at all"), (1, 'All as warning'), (2, 'As is')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
