# Generated by Django 5.0.6 on 2024-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfmeasunit',
            old_name='conv_factor',
            new_name='coeff',
        ),
        migrations.AddField(
            model_name='datafeedtype',
            name='is_totalizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dfmeasunit',
            name='adder',
            field=models.FloatField(default=0.0),
        ),
    ]
