# Generated by Django 5.0.6 on 2024-06-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfReading',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('reading', models.FloatField(null=True)),
                ('datafeed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datafeeds.datafeed')),
            ],
            options={
                'db_table': 'dfreadings',
            },
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('dfreadings', 'timestamp');
            """,
            reverse_sql="""
                DROP TABLE dfreadings;
            """
        )
    ]
